// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyt8G14Es0dsxMLAq_-Ef_vvwKCKtxftE',
    appId: '1:701982697127:web:c7a9fdc326310b01b59d82',
    messagingSenderId: '701982697127',
    projectId: 'kitahack--2026',
    authDomain: 'kitahack--2026.firebaseapp.com',
    storageBucket: 'kitahack--2026.firebasestorage.app',
    measurementId: 'G-G6DX3DKGGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiyWoSkyszzt-tflZGTWsBzsjO1kDb1bw',
    appId: '1:701982697127:android:484f3d8dd9a98726b59d82',
    messagingSenderId: '701982697127',
    projectId: 'kitahack--2026',
    storageBucket: 'kitahack--2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLdE6WCqhl6L4ZnplQ6lddJkrE1ZJjGlk',
    appId: '1:701982697127:ios:1cd8ec29badfbd9bb59d82',
    messagingSenderId: '701982697127',
    projectId: 'kitahack--2026',
    storageBucket: 'kitahack--2026.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLdE6WCqhl6L4ZnplQ6lddJkrE1ZJjGlk',
    appId: '1:701982697127:ios:1cd8ec29badfbd9bb59d82',
    messagingSenderId: '701982697127',
    projectId: 'kitahack--2026',
    storageBucket: 'kitahack--2026.firebasestorage.app',
    iosBundleId: 'com.example.kitahack2026',
  );
}
